server:
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  application:
    name: service-feign

# 开启断路器
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000



