
spring:
  application:
    name: gateway
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mayjors/mycloud.git #uri
          search-paths: /** #配置文件目录
      label: master
      username: 983534678@qq.com #github账号
      password: yuanjie219314 #github密码


server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


