
spring:
  application:
    name: gateway

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

zuul:
  routes:
    user:
      path: /test/**
      serviceId: service-manager
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000

order-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

#超时配置说明：
#如果路由方式是serviceId的方式，配置为：zuul:routes:order:serviceId，那么ribbon的超时配置生效（order-service:ribbon:ReadTimeout）
#如果如果是url的方式，配置为：zuul:routes:order:url，则zuul.host开头的生效
