server:
  port: 1234

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/

# 打印日志
#logging:
#  level:
#    root: INFO
#    com.springms: DEBUG

info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false