package rules

import com.eu.servicedrools.entity.Address;
import com.eu.servicedrools.entity.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"

    when
//        address : Address(postcode != null, postcode matches "([0-9]{5})")
        address : Address(postcode == "99425")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
		System.out.println("规则中打印日志：校验通过!");
end