# eureka注册中心
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:1111/eureka/
server:
  port: 9000

spring:
  application:
    name: server-zipkin
#  zipkin:
#    enabled: true
#    baseUrl: http://localhost:9000/
#  sleuth:
#    sampler:
#      percentage: 1

